apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-v2
  namespace: guestbook
  labels:
    app: guestbook
    version: "2.0"
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: guestbook
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
        version: "2.0"
    spec:
      containers:
      - name: guestbook
        image: sebkhedim/guestbook:0.1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  namespace: guestbook
  labels:
    app: guestbook
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: guestbook
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  namespace: guestbook
spec:
  rules:
  - host: 34.141.182.0.xip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook
            port:
              number: 80